#SPDX-License-Identifier: MIT-0
# vars file for setup
git_username: "mvaldes14"
git_repos:
  - dotfiles
  - k8s-apps
  - twitch-bot
  - blog
  - terraform
  - dotfiles-nix
  - ansible_playbooks
  - meal-notifier
  - gh-actions
  - terraform.nvim
  - chef
  - vorpal
  - todoist.nvim
  - linear.nvim
  - aoc
  - server_scraper
  - deckmaster-config
  - pulumi
username: "mvaldes"
username_home: "/home/mvaldes"
