# SPDX-License-Identifier: MIT-0
---
# defaults file for setup

# Username for SSH access configuration
username: mvaldes

# Enable/disable pihole service management
pihole_enabled: false

# Enable/disable OTEL collector agent
otel_enabled: false
