- name: Setup SSH Things
  environment:
    user: "mvaldes"
  block:
    - name: Install ssh package
      ansible.builtin.apt:
        name: openssh-server
        state: present
        update_cache: true
    - name: SSH Config
      ansible.builtin.copy:
        src: "sshd_config.j2"
        dest: "/etc/ssh/sshd_config"
        mode: "0644"
        owner: root
        group: root
      notify: RestartSSH
    - name: Get Certificate
      ansible.builtin.get_url:
        url: https://vault.mvaldes.dev/v1/ssh/public_key
        dest: "/etc/ssh/vault-cert.pub"
        mode: "0644"
    - name: Commands Without Sudo
      become: true
      community.general.sudoers:
        name: sudoers-mvaldes-nopasswd
        state: present
        user: mvaldes
        commands:
          - /usr/bin/systemctl restart ssh
          - /usr/bin/apt update
          - /usr/bin/apt upgrade
        nopassword: true
