- name: Install applications for Ubuntu
  tags:
    - pkg
  block:
    - name: Setup Structure
      include_tasks: structure.yml
    - name: Setup SSH Access
      include_tasks: access.yml
    - name: Setup Otel Agent
      ansible.builtin.include_tasks: otel.yml
      when: otel_enabled | default(true)
    - name: Setup MOTD
      include_tasks: motd.yml
