driver:
  name: docker
platforms:
  - name: dotfiles-test
    image: ubuntu:24.04
    pre_build_image: false
    dockerfile: ./Dockerfile
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible-${USER}/tmp
verifier:
  name: ansible
scenario:
  test_sequence:
    - converge
    - verify
