driver:
  name: docker
platforms:
  - name: dotfiles-test
    image: ubuntu:24.04
    pre_build_image: false
    dockerfile: ./Dockerfile
    command: ""
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
verifier:
  name: ansible
scenario:
  test_sequence:
    - converge
    - verify
