#SPDX-License-Identifier: MIT-0
# vars file for setup
base_apps:
  - neovim
  - tmux
  - fd-find
  - ripgrep
  - zsh
  - tree
  - gh
  - jq
  - bind9-dnsutils
  - htop
  - bat
  - fzf
git_username: 'mvaldes14'
git_repos:
  - dotfiles
  - k8s-apps
  - twitch-bot
  - blog
  - terraform
  - dotfiles-nix
  - ansible_playbooks
  - meal-notifier
  - gh-actions
  - terraform.nvim
  - chef
  - vorpal
  - todoist.nvim
  - linear.nvim
  - aoc
  - server_scraper
  - deckmaster-config
  - pulumi
username_home: '/home/mvaldes'
