# Connection settings
ansible_user: mvaldes

# User configuration
username: mvaldes
username_home: "/home/{{ username }}"

# Node architecture
node_arch: arm64

# Service toggles
pihole_enabled: false
otel_enabled: false
